version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: securedb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  secure-backend:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: securedb
      POSTGRES_HOST: db
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    restart: always

volumes:
  pgdata:
